apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Release.Namespace | default "default" | quote }}
data:
  config.yml: |-
{{ printf .Values.config | indent 4 }}
