apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: bintangbahy/kube-restart:{{ .Values.version }}
          volumeMounts:
            - name: config
              mountPath: /etc/kube-restart/
      volumes:
        - name: config
          configMap:
            name: {{ .Values.name }}-config
            items:
              - key: config.yml
                path: config.yml
