apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    app: {{ .Values.name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
rules:
  - apiGroups:
      - "apps"
    resources:
      - "deployments"
      - "statefulsets"
    verbs:
      - "get"
      - "list"
      - "update"
      - "patch"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace | default "default" | quote }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}
    namespace: {{ .Release.Namespace | default "default" | quote }}
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Values.name }}
  apiGroup: ""
